class Day9Flow
  DAY_9_FLOWS = {
    say_hello: { next: "get_hello_response" },
    say_hello_from_skip: { next: "get_intro_1_response" },
    say_hello_from_catch_up: { next: "get_intro_1_response" },
    get_hello_response: { next: "say_intro_1" },
    say_intro_1: { next: "get_intro_1_response" },
    get_intro_1_response: { next: "say_intro_2" },
    say_intro_2: { next: "get_intro_2_response" },
    get_intro_2_response: { next: "say_review_1" },
    say_review_1: { next: "get_reviews_1_response" },
    get_reviews_1_response: { next: "say_review_2" },
    say_review_2: { next: "get_reviews_2_response" },
    get_reviews_2_response: { next: "say_review_3" },
    say_review_3: { next: "get_reviews_3_response" },
    get_reviews_3_response: { next: "say_review_4" },
    say_review_4: { next: "get_reviews_4_response" },
    get_reviews_4_response: { next: "say_review_5" },
    say_review_5: { next: "get_reviews_5_response" },
    get_reviews_5_response: { next: "say_review_6" },
    say_review_6: { next: "get_reviews_6_response" },
    get_reviews_6_response: { next: "say_review_7" },
    say_review_7: { next: "get_reviews_7_response" },
    get_reviews_7_response: { next: "say_review_8" },
    say_review_8: { next: "get_reviews_8_response" },
    get_reviews_8_response: { next: "say_review_9" },
    say_review_9: { next: "get_reviews_9_response" },
    get_reviews_9_response: { next: "say_review_10" },
    say_review_10: { next: "get_reviews_10_response" },
    get_reviews_10_response: { next: "say_review_11" },
    say_review_11: { next: "get_reviews_11_response" },
    get_reviews_11_response: { next: "say_review_12" },
    say_review_12: { next: "get_reviews_12_response" },
    get_reviews_12_response: { next: "say_review_13" },
    say_review_13: { next: "get_reviews_13_response" },
    get_reviews_13_response: { next: "say_wrap_up_1" },
    say_wrap_up_1: { next: "get_wrap_up_1_response" },
    get_wrap_up_1_response: { next: "say_wrap_up_2" },
    say_wrap_up_2: { next: "get_wrap_up_2_response" },
    get_wrap_up_2_response: { next: "say_goodbye" }
  }
end